In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('StudentPerformanceFactors.csv')

In [3]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [4]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [5]:
#dataset summary
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   str
 3   Access_to_Resources         6607 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   str
 11  Teacher_Quality             6529 non-null   str
 12  School_Type                 6607 non-null   str
 13  Peer_Influence              6607 non-null   str
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   str
 16  Parental_Education_Level    6517 non-null   str
 17  Distance_from_Home          6540 non-null   str
 18  Gender                      6607 non-null   str
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), str(13)
memory usage: 1.0 MB

In [6]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [7]:
missing_values = df.isnull().sum()

missing_values[missing_values>0]

Teacher_Quality             78
Parental_Education_Level    90
Distance_from_Home          67
dtype: int64

In [8]:
#to handle missing values, use backward fill
df_fill = df.bfill()

df_fill.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64

In [9]:
#drop duplicates
df.drop_duplicates(inplace=True)

In [10]:
df.shape

(6607, 20)

In [11]:
#detect outliers
df.select_dtypes(include=['float64', 'int64']).skew()

Hours_Studied        0.013499
Attendance           0.013666
Sleep_Hours         -0.023805
Previous_Scores     -0.003737
Tutoring_Sessions    0.815530
Physical_Activity   -0.031365
Exam_Score           1.644808
dtype: float64

In [12]:
from scipy import stats
#Hours_Studied
#z-scores
df['Z_score'] = stats.zscore(df['Hours_Studied'])

#set threshold
outliers = df[df['Z_score'].abs() > 3]

outliers

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Z_score
209,43,86,High,Medium,Yes,7,97,Medium,Yes,2,...,High,Public,Positive,1,No,High School,Near,Female,78,3.843761
262,1,69,High,Medium,Yes,6,97,Medium,Yes,1,...,Medium,Public,Positive,3,No,High School,Near,Female,61,-3.167760
478,38,86,Low,High,Yes,7,79,Low,Yes,3,...,Medium,Public,Negative,3,No,High School,Near,Male,73,3.009056
1591,2,84,Low,High,No,8,54,Low,Yes,3,...,Low,Public,Positive,4,No,NaN,Near,Male,62,-3.000819
1615,39,95,Medium,High,Yes,9,54,High,Yes,2,...,Medium,Private,Positive,3,No,High School,Moderate,Male,77,3.175997
1957,39,97,High,High,Yes,10,91,Medium,Yes,2,...,Medium,Public,Positive,3,No,High School,Moderate,Female,79,3.175997
1971,2,96,Low,High,Yes,9,77,Medium,Yes,3,...,NaN,Public,Neutral,2,No,High School,Far,Female,65,-3.000819
2024,2,98,Low,High,Yes,7,80,High,Yes,2,...,High,Public,Neutral,1,No,High School,Near,Male,66,-3.000819
2305,39,92,Medium,Medium,No,9,73,Medium,Yes,1,...,Medium,Public,Negative,4,No,Postgraduate,Moderate,Male,75,3.175997
2506,38,63,Medium,High,No,8,52,High,Yes,1,...,Medium,Private,Positive,3,No,College,Moderate,Male,69,3.009056
2521,38,86,High,Medium,No,6,88,High,Yes,1,...,High,Public,Negative,4,No,High School,Moderate,Female,74,3.009056
2895,44,68,High,Low,No,9,75,Low,Yes,3,...,High,Private,Negative,2,No,High School,Moderate,Female,71,4.010702
2947,2,67,Medium,Medium,No,6,73,Low,Yes,1,...,Medium,Private,Positive,2,No,College,Moderate,Male,58,-3.000819
3454,2,99,Medium,Low,Yes,9,52,Low,Yes,0,...,Medium,Public,Neutral,4,No,High School,Near,Male,62,-3.000819
3716,39,90,High,High,No,8,92,High,Yes,2,...,High,Private,Neutral,1,No,High School,Near,Female,78,3.175997
3982,39,75,Medium,High,Yes,6,82,High,Yes,1,...,Low,Public,Negative,3,No,College,Near,Male,73,3.175997
4198,2,98,High,Medium,No,4,64,Medium,Yes,1,...,High,Private,Neutral,2,No,High School,Near,Female,65,-3.000819
4725,1,81,Medium,Medium,Yes,8,66,Medium,Yes,1,...,Medium,Public,Negative,2,No,College,Near,Male,60,-3.167760
4779,1,88,Medium,High,Yes,4,72,High,Yes,3,...,Medium,Private,Negative,2,No,College,Near,Male,92,-3.167760
4870,38,90,High,Medium,Yes,4,60,Low,Yes,2,...,Medium,Public,Neutral,4,No,College,Moderate,Male,74,3.009056
4997,39,67,High,High,Yes,5,76,Medium,No,2,...,Medium,Private,Negative,4,No,NaN,Near,Female,71,3.175997
5157,38,82,Medium,Low,No,6,97,Low,Yes,2,...,Medium,Private,Negative,3,No,College,Near,Male,72,3.009056
5224,38,80,High,Medium,No,5,78,Medium,Yes,1,...,Medium,Public,Positive,4,No,College,Far,Female,72,3.009056
5796,39,78,Medium,Medium,No,6,73,Medium,Yes,0,...,Medium,Public,Positive,2,No,College,Far,Male,70,3.175997
5846,38,98,Low,Medium,No,6,94,Medium,Yes,2,...,Low,Public,Negative,4,No,Postgraduate,Near,Female,75,3.009056

In [13]:
import numpy as np
#for skewed data, use median else use mean

z_scores = np.abs(stats.zscore(df['Hours_Studied']))

threshold = 3
# 5. Calculate the imputation value (mean of non-outliers)
mean_value = int(df['Hours_Studied'].mean())

df['Hours_Studied'] = np.where(z_scores > threshold, mean_value, df['Hours_Studied'])

print(f"\nMean of non-outliers used for imputation: {mean_value}")

print("\nDataFrame after imputation:")
print(df[['Hours_Studied']])

Mean of non-outliers used for imputation: 19

DataFrame after imputation:
      Hours_Studied
0                23
1                19
2                24
3                29
4                19
...             ...
6602             25
6603             23
6604             20
6605             10
6606             15

[6607 rows x 1 columns]

In [14]:
#Attendance
#z-scores
df['Z_score'] = stats.zscore(df['Attendance'])

#set threshold
outliers = df[df['Z_score'].abs() > 3]

outliers

Empty DataFrame
Columns: [Hours_Studied, Attendance, Parental_Involvement, Access_to_Resources, Extracurricular_Activities, Sleep_Hours, Previous_Scores, Motivation_Level, Internet_Access, Tutoring_Sessions, Family_Income, Teacher_Quality, School_Type, Peer_Influence, Physical_Activity, Learning_Disabilities, Parental_Education_Level, Distance_from_Home, Gender, Exam_Score, Z_score]
Index: []

[0 rows x 21 columns]

In [15]:
#Sleep_Hours 
#z-scores
df['Z_score'] = stats.zscore(df['Sleep_Hours'])

#set threshold
outliers = df[df['Z_score'].abs() > 3]

outliers

Empty DataFrame
Columns: [Hours_Studied, Attendance, Parental_Involvement, Access_to_Resources, Extracurricular_Activities, Sleep_Hours, Previous_Scores, Motivation_Level, Internet_Access, Tutoring_Sessions, Family_Income, Teacher_Quality, School_Type, Peer_Influence, Physical_Activity, Learning_Disabilities, Parental_Education_Level, Distance_from_Home, Gender, Exam_Score, Z_score]
Index: []

[0 rows x 21 columns]

In [16]:
#Previous_Scores
#z-scores
df['Z_score'] = stats.zscore(df['Previous_Scores'])

#set threshold
outliers = df[df['Z_score'].abs() > 3]

outliers

Empty DataFrame
Columns: [Hours_Studied, Attendance, Parental_Involvement, Access_to_Resources, Extracurricular_Activities, Sleep_Hours, Previous_Scores, Motivation_Level, Internet_Access, Tutoring_Sessions, Family_Income, Teacher_Quality, School_Type, Peer_Influence, Physical_Activity, Learning_Disabilities, Parental_Education_Level, Distance_from_Home, Gender, Exam_Score, Z_score]
Index: []

[0 rows x 21 columns]

In [17]:
#Tutoring_Sessions
#z-scores
df['Z_score'] = stats.zscore(df['Tutoring_Sessions'])

#set threshold
outliers = df[df['Z_score'].abs() > 3]

outliers

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Z_score
679,28,65,Medium,Medium,Yes,4,64,Medium,Yes,6,...,High,Public,Neutral,3,No,Postgraduate,Near,Male,70,3.662222
724,21,73,Medium,Medium,No,6,85,Medium,Yes,6,...,High,Public,Neutral,5,No,College,Near,Male,70,3.662222
1462,19,62,High,Medium,Yes,6,79,Low,Yes,7,...,Medium,Public,Neutral,2,No,High School,Near,Female,66,4.474915
1548,25,95,Low,Medium,No,7,78,Medium,Yes,7,...,Medium,Public,Positive,4,No,High School,Near,Male,73,4.474915
1848,26,93,High,Low,No,6,94,Medium,Yes,6,...,Medium,Private,Negative,4,No,High School,Near,Female,74,3.662222
2040,16,66,Low,Medium,No,6,93,Medium,Yes,7,...,Medium,Public,Negative,2,No,High School,Far,Male,63,4.474915
2198,16,92,Medium,Medium,Yes,4,90,High,Yes,6,...,Medium,Private,Neutral,3,No,High School,Near,Male,72,3.662222
2231,25,72,Low,Low,Yes,6,78,Low,Yes,8,...,High,Public,Positive,4,No,High School,Near,Male,69,5.287608
2237,14,81,Low,Medium,No,6,89,Medium,No,6,...,High,Private,Neutral,3,No,College,Near,Female,67,3.662222
2265,27,97,High,High,No,8,72,Medium,Yes,6,...,Medium,Public,Neutral,2,No,College,Near,Female,76,3.662222
2346,17,91,High,Low,Yes,10,84,Medium,Yes,7,...,High,Public,Neutral,4,Yes,College,Moderate,Male,71,4.474915
2699,28,86,Low,Medium,No,10,85,Medium,Yes,6,...,High,Public,Neutral,2,No,High School,Near,Male,72,3.662222
2718,16,72,High,Medium,Yes,9,76,High,Yes,6,...,Low,Public,Negative,3,No,High School,Near,Male,67,3.662222
3388,25,94,High,High,No,8,96,High,Yes,6,...,Medium,Public,Negative,3,Yes,High School,Far,Female,74,3.662222
3617,18,95,Medium,High,Yes,6,94,Medium,Yes,6,...,High,Public,Neutral,3,No,High School,Far,Female,73,3.662222
3880,22,97,High,Medium,Yes,5,68,Low,Yes,7,...,High,Private,Negative,5,No,College,Near,Female,75,4.474915
3894,18,72,Low,High,No,7,58,Low,Yes,6,...,Medium,Public,Positive,0,No,High School,Moderate,Male,64,3.662222
4009,24,69,High,Medium,No,7,69,Medium,No,7,...,Medium,Public,Positive,3,No,College,Near,Female,70,4.474915
4091,29,94,High,Medium,No,7,79,Medium,Yes,6,...,High,Private,Neutral,4,No,College,Near,Female,76,3.662222
4247,33,92,High,High,Yes,7,67,Low,Yes,6,...,Medium,Public,Positive,5,No,High School,Near,Female,78,3.662222
4697,28,99,High,Low,No,5,100,Medium,Yes,6,...,Medium,Private,Neutral,5,No,High School,Moderate,Female,76,3.662222
4799,24,98,Medium,High,No,8,61,Medium,Yes,6,...,High,Private,Positive,3,No,High School,Near,Female,75,3.662222
5680,14,82,Medium,High,No,6,94,Low,Yes,7,...,High,Private,Negative,4,No,Postgraduate,Near,Male,71,4.474915
5855,9,64,Medium,High,Yes,6,99,Medium,Yes,6,...,High,Public,Positive,6,Yes,High School,Moderate,Male,65,3.662222
6061,24,67,High,Low,No,6,86,Medium,Yes,6,...,Medium,Private,Positive,3,Yes,Postgraduate,Moderate,Female,67,3.662222
6485,35,84,Low,Medium,Yes,8,92,High,Yes,6,...,High,Public,Negative,4,No,High School,Moderate,Male,74,3.662222

In [18]:
z_scores = np.abs(stats.zscore(df['Tutoring_Sessions']))

threshold = 3
# 5. Calculate the imputation value (median of non-outliers)
median_value = int(df['Tutoring_Sessions'].median())

df['Tutoring_Sessions'] = np.where(z_scores > threshold, median_value, df['Tutoring_Sessions'])

print(f"\nMedian of non-outliers used for imputation: {median_value}")

print("\nDataFrame after imputation:")
print(df[['Tutoring_Sessions']])

Median of non-outliers used for imputation: 1

DataFrame after imputation:
      Tutoring_Sessions
0                     0
1                     2
2                     2
3                     1
4                     3
...                 ...
6602                  1
6603                  3
6604                  3
6605                  2
6606                  0

[6607 rows x 1 columns]

In [19]:
#Physical_Activity
#z-scores
df['Z_score'] = stats.zscore(df['Physical_Activity'])

#set threshold
outliers = df[df['Z_score'].abs() > 3]

outliers

Empty DataFrame
Columns: [Hours_Studied, Attendance, Parental_Involvement, Access_to_Resources, Extracurricular_Activities, Sleep_Hours, Previous_Scores, Motivation_Level, Internet_Access, Tutoring_Sessions, Family_Income, Teacher_Quality, School_Type, Peer_Influence, Physical_Activity, Learning_Disabilities, Parental_Education_Level, Distance_from_Home, Gender, Exam_Score, Z_score]
Index: []

[0 rows x 21 columns]

In [20]:
df.drop(columns = ['Z_score'])

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [21]:
#Exam_Score
#IQR
Q1 = df['Exam_Score'].quantile(0.25)
Q3 = df['Exam_Score'].quantile(0.75)
IQR = Q3-Q1

lb = Q1 - 1.5 * IQR
ub = Q3 + 1.5 * IQR

outliers = df[(df['Exam_Score'] < lb) | (df['Exam_Score'] > ub)]

outliers

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Z_score
94,18,89,High,Medium,Yes,4,73,Medium,Yes,3,...,Medium,Private,Positive,2,No,College,Near,Female,100,-0.938377
106,31,100,Medium,Medium,No,7,59,Medium,Yes,2,...,High,Public,Positive,5,No,Postgraduate,Moderate,Male,76,1.970988
113,35,99,High,High,Yes,7,85,Low,Yes,2,...,High,Private,Neutral,2,No,Postgraduate,Near,Female,79,-0.938377
209,19,86,High,Medium,Yes,7,97,Medium,Yes,2,...,High,Public,Positive,1,No,High School,Near,Female,78,-1.908165
217,19,70,Medium,Low,No,7,54,High,Yes,0,...,Medium,Public,Positive,2,Yes,High School,Moderate,Male,89,-0.938377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6347,28,96,High,Low,Yes,4,98,High,Yes,1,...,High,Public,Positive,3,No,High School,Near,Male,98,0.031411
6393,16,83,Low,Medium,Yes,8,92,Low,Yes,2,...,High,Public,Positive,4,No,Postgraduate,Near,Female,98,1.001199
6431,4,60,Medium,Medium,Yes,7,55,Medium,Yes,2,...,Medium,Private,Neutral,2,No,Postgraduate,Near,Male,58,-0.938377
6522,18,90,High,High,Yes,6,54,Low,Yes,1,...,High,Public,Negative,3,No,High School,Near,Female,95,0.031411
6566,29,96,High,Medium,No,8,85,Low,Yes,3,...,Medium,Public,Neutral,3,No,Postgraduate,Near,Male,76,0.031411

In [22]:
z_scores = np.abs(stats.zscore(df['Exam_Score']))

threshold = 3
# 5. Calculate the imputation value (median of non-outliers)
median_value = int(df['Exam_Score'].median())

df['Exam_Score'] = np.where(z_scores > threshold, median_value, df['Exam_Score'])

print(f"\nMedian of non-outliers used for imputation: {median_value}")

print("\nDataFrame after imputation:")
print(df[['Exam_Score']])

Median of non-outliers used for imputation: 67

DataFrame after imputation:
      Exam_Score
0             67
1             61
2             74
3             71
4             70
...          ...
6602          68
6603          69
6604          68
6605          68
6606          64

[6607 rows x 1 columns]

In [23]:
#Datatype Conversion
df.dtypes

Hours_Studied                   int64
Attendance                      int64
Parental_Involvement              str
Access_to_Resources               str
Extracurricular_Activities        str
Sleep_Hours                     int64
Previous_Scores                 int64
Motivation_Level                  str
Internet_Access                   str
Tutoring_Sessions               int64
Family_Income                     str
Teacher_Quality                   str
School_Type                       str
Peer_Influence                    str
Physical_Activity               int64
Learning_Disabilities             str
Parental_Education_Level          str
Distance_from_Home                str
Gender                            str
Exam_Score                      int64
Z_score                       float64
dtype: object

In [24]:
#for binary attributes
pd.set_option('future.no_silent_downcasting', True)
from sklearn.preprocessing import LabelEncoder

df['Extracurricular_Activities'] = df['Extracurricular_Activities'].replace({'Yes': 1, 'No': 0})

df['Internet_Access'] = df['Internet_Access'].replace({'Yes': 1, 'No': 0})
df['Learning_Disabilities'] = df['Learning_Disabilities'].replace({'Yes': 1, 'No': 0})

C:\Users\anosh\AppData\Local\Temp\ipykernel_18028\366915888.py:2: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.set_option('future.no_silent_downcasting', True)

In [25]:
#for ordinal attributes

# Define the order manually
size_map = {'Low': 1, 'Medium': 2, 'High': 3}
df['Parental_Involvement'] = df['Parental_Involvement'].replace(size_map)

df['Access_to_Resources'] = df['Access_to_Resources'].replace(size_map)

df['Motivation_Level'] = df['Motivation_Level'].replace(size_map)

df['Family_Income'] = df['Family_Income'].replace(size_map)

df['Teacher_Quality'] = df['Teacher_Quality'].replace(size_map)

size_map2 = {'Negative': 1, 'Neutral': 2, 'Positive': 3}
df['Peer_Influence'] = df['Peer_Influence'].replace(size_map2)

size_map3 = {'Near': 1, 'Moderate': 2, 'Far': 3}
df['Distance_from_Home'] = df['Distance_from_Home'].replace(size_map3)

In [26]:
#for nominal attributes
try:
    df = pd.get_dummies(df, columns=['School_Type', 'Parental_Education_Level', 'Gender'], prefix=['School_Type', 'PEL', 'Gender'], drop_first=False, dtype=int)      
#Ensures results are 1/0, not True/False
except KeyError:
    pass # This ignores the error silently

In [27]:
df = df.drop(columns = ['Z_score'])
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Learning_Disabilities,Distance_from_Home,Exam_Score,School_Type_Private,School_Type_Public,PEL_College,PEL_High School,PEL_Postgraduate,Gender_Female,Gender_Male
0,23,84,1,3,0,7,73,1,1,0,...,0,1,67,0,1,0,1,0,0,1
1,19,64,1,2,0,8,59,1,1,2,...,0,2,61,0,1,1,0,0,1,0
2,24,98,2,2,1,7,91,2,1,2,...,0,1,74,0,1,0,0,1,0,1
3,29,89,1,2,1,8,98,2,1,1,...,0,2,71,0,1,0,1,0,0,1
4,19,92,2,2,1,6,65,2,1,3,...,0,1,70,0,1,1,0,0,1,0

In [28]:
#update csv file
df.to_csv('StudentPerformanceFactors_updated.csv', index=False)

Deliverable 2: Machine Learning Implementation

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  Peer_Influence              6607 non-null   object
 13  Physical_Activity           6607 non-null   int64
 14  Learning_Disabilities       6607 non-null   object
 15  Distance_from_Home          6540 non-null   object
 16  Exam_Score                  6607 non-null   int64
 17  School_Type_Private         6607 non-null   int64
 18  School_Type_Public          6607 non-null   int64
 19  PEL_College                 6607 non-null   int64
 20  PEL_High School             6607 non-null   int64
 21  PEL_Postgraduate            6607 non-null   int64
 22  Gender_Female               6607 non-null   int64
 23  Gender_Male                 6607 non-null   int64
dtypes: int64(14), object(10)
memory usage: 1.2+ MB

In [31]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Learning_Disabilities,Distance_from_Home,Exam_Score,School_Type_Private,School_Type_Public,PEL_College,PEL_High School,PEL_Postgraduate,Gender_Female,Gender_Male
0,23,84,1,3,0,7,73,1,1,0,...,0,1,67,0,1,0,1,0,0,1
1,19,64,1,2,0,8,59,1,1,2,...,0,2,61,0,1,1,0,0,1,0
2,24,98,2,2,1,7,91,2,1,2,...,0,1,74,0,1,0,0,1,0,1
3,29,89,1,2,1,8,98,2,1,1,...,0,2,71,0,1,0,1,0,0,1
4,19,92,2,2,1,6,65,2,1,3,...,0,1,70,0,1,1,0,0,1,0

In [32]:
df[['Extracurricular_Activities', 'Parental_Involvement', 'School_Type_Public']].head()

  Extracurricular_Activities Parental_Involvement  School_Type_Public
0                          0                    1                   1
1                          0                    1                   1
2                          1                    2                   1
3                          1                    1                   1
4                          1                    2                   1

In [33]:
#to force all columns to numeric, turning any leftover text into 'NaN'
df = df.apply(pd.to_numeric, errors='coerce')

print(df.isnull().sum().sum())

145

In [35]:
print(df.isnull().sum())

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Distance_from_Home            67
Exam_Score                     0
School_Type_Private            0
School_Type_Public             0
PEL_College                    0
PEL_High School                0
PEL_Postgraduate               0
Gender_Female                  0
Gender_Male                    0
dtype: int64

In [36]:
df['Teacher_Quality'] = df['Teacher_Quality'].bfill()
df['Distance_from_Home'] = df['Distance_from_Home'].bfill()

In [37]:
print(df.isnull().sum()) #final verification

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Distance_from_Home            0
Exam_Score                    0
School_Type_Private           0
School_Type_Public            0
PEL_College                   0
PEL_High School               0
PEL_Postgraduate              0
Gender_Female                 0
Gender_Male                   0
dtype: int64

In [38]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Learning_Disabilities,Distance_from_Home,Exam_Score,School_Type_Private,School_Type_Public,PEL_College,PEL_High School,PEL_Postgraduate,Gender_Female,Gender_Male
0,23,84,1,3,0,7,73,1,1,0,...,0,1.0,67,0,1,0,1,0,0,1
1,19,64,1,2,0,8,59,1,1,2,...,0,2.0,61,0,1,1,0,0,1,0
2,24,98,2,2,1,7,91,2,1,2,...,0,1.0,74,0,1,0,0,1,0,1
3,29,89,1,2,1,8,98,2,1,1,...,0,2.0,71,0,1,0,1,0,0,1
4,19,92,2,2,1,6,65,2,1,3,...,0,1.0,70,0,1,1,0,0,1,0

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   int64
 3   Access_to_Resources         6607 non-null   int64
 4   Extracurricular_Activities  6607 non-null   int64
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   int64
 8   Internet_Access             6607 non-null   int64
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   int64
 11  Teacher_Quality             6607 non-null   float64
 12  Peer_Influence              6607 non-null   int64
 13  Physical_Activity           6607 non-null   int64
 14  Learning_Disabilities       6607 non-null   int64
 15  Distance_from_Home          6607 non-null   float64
 16  Exam_Score                  6607 non-null   int64
 17  School_Type_Private         6607 non-null   int64
 18  School_Type_Public          6607 non-null   int64
 19  PEL_College                 6607 non-null   int64
 20  PEL_High School             6607 non-null   int64
 21  PEL_Postgraduate            6607 non-null   int64
 22  Gender_Female               6607 non-null   int64
 23  Gender_Male                 6607 non-null   int64
dtypes: float64(2), int64(22)
memory usage: 1.2 MB

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn import metrics
import numpy as np

y = df['Exam_Score'] #target variable
X = df.drop('Exam_Score', axis=1) #features

In [41]:
X.shape #features dataset

(6607, 23)

In [42]:
y.shape #target dataset

(6607,)

In [43]:
#split data: 80% Training, 20% Testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape[0]}")
print(f"Testing set size: {X_test.shape[0]}")

Training set size: 5285
Testing set size: 1322

In [44]:
#now we need to apply feature scaling on the split data [X]:

#use standardization for symmetric distribution to scale it around variance. it centers the data at a mean of 0.
#all skewness values are now not very high since we already handled outliers
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

#fit_transform on training dataset, only transform on testing dataset
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Linear Regression

In [45]:
LR_model = LinearRegression()

In [46]:
LR_model.fit(X_train_scaled, y_train)

LinearRegression()

In [47]:
#make predictions
LR_predict = LR_model.predict(X_test_scaled)

Random Forest Regressor

In [48]:
from sklearn.ensemble import RandomForestRegressor

RFR_model = RandomForestRegressor(n_estimators=100, random_state=42)

In [49]:
RFR_model.fit(X_train_scaled, y_train)

RandomForestRegressor(random_state=42)

In [50]:
RFR_predict = RFR_model.predict(X_test_scaled)

Results Comparison

In [51]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

results = {
    "Metric": ["MAE", "RMSE", "R2 Score"],
    "Linear Regression": [
        mean_absolute_error(y_test, LR_predict),
        np.sqrt(mean_squared_error(y_test, LR_predict)),
        r2_score(y_test, LR_predict)
    ],
    "Random Forest": [
        mean_absolute_error(y_test, RFR_predict),
        np.sqrt(mean_squared_error(y_test, RFR_predict)),
        r2_score(y_test, RFR_predict)
    ]
}

final_results = pd.DataFrame(results)
print(final_results)

     Metric  Linear Regression  Random Forest
0       MAE           0.342041       0.878313
1      RMSE           0.704148       1.189951
2  R2 Score           0.955074       0.871700

In [52]:
#Linear Regression has a very high R2 score of around 96% (rounded up). 
# This means our independent variables are able to explain 96% variance in student grades.
#MAE is also low around 0.34, indicating that on average
#our model's prediction is just 0.34 points away from the actual score
#hence we will choose Linear Regression over Random Forest Regressor

Winner: Linear Regression